### ISSUE TITLE
Detected corrupted documents without _id identifier

### ISSUE THREAD

**Issue by ivanlopezmolina** [Azure-Samples/documentdb-dotnet-core-getting-started#11]
Hi, I'm using Azure Cosmos DB, the code seems to be working in a core 2 web api, however when I try to see the data in azure I get the following message:

{"code":500,"body":"Detected corrupted documents without _id identifier, verify that you are only storing documents through Mongo protocol and not SQL API or DocumentDB SDK."}

it seems the code doesn't add an _id for the collection document, any ideas what could be missing?.

Thanks.

**Comment by suleymanov** [comment]
+1
I added "_id" field manually, still it doesn't appear.

**Comment by ivanlopezmolina** [comment]
@suleymanov I was using the wrong API, you must select SQL instead MongoDB in the API dropdown when creating a new cosmos DB, 

Regards.
