### ISSUE TITLE
Question: why no net452 support?

### ISSUE THREAD

**Issue by brockallen** [Azure-Samples/documentdb-dotnet-core-getting-started#3]
I see on nuget (https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/) that this package only supports netstandard16. Why is there no net452 support like pretty much everything thing else in ASP.NET core -- here's MVC for example (which even is net451): https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc/

In short, is this library only supported on .NET Core? If so, then why can't support be extended to the full .NET framework (since netstandard16 doesn't run on the full .NET framework: https://docs.microsoft.com/en-us/dotnet/articles/standard/library). 

This prevents me from building apps that require the full .NET framework from using this DocumentDb library.

**Comment by mingaliu** [comment]
Hi 
    We have full .NET framework support at  https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/    Does this fill your needs?

**Comment by brockallen** [comment]
I'll give it a try and will let you know -- thanks.

**Comment by brockallen** [comment]
Ok, I think it's working. Out of curiosity -- why not just have one assembly support both targets?

**Comment by mingaliu** [comment]
It doesn't support. Even the nugget package https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc/ actually has two binaries support net452  and netstandard respectively.

**Comment by brockallen** [comment]
Sure, but MVC is one NuGet, not one for each target runtime.

**Comment by rnagpal** [comment]
@brockallen  We plan to have a single Nuget package for both target runtimes in near future.

**Comment by brockallen** [comment]
Ok, thanks for the info.
